apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: ecom
data: 
  AMQP_USER: "cm9ib3Nob3A=" 
  AMQP_PASS: "cm9ib3Nob3AxMjM=" 
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: rabbitmq
  namespace: ecom
  labels: 
    name: rabbitmq
    project: ecomApp
    tier: db
spec: 
  replicas: 1
  selector:
    matchLabels: 
      name: rabbitmq
      project: ecomapp
      tier: db
  template:
    metadata:
      labels:
        name: rabbitmq
        project: ecomapp
        tier: db
    spec: 
      containers: 
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - secretRef:
            name: rabbitmq
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
  namespace: ecom
  labels:
    name: rabbitmq
    project: ecomapp
    tier: db
spec:
  selector:
    name: rabbitmq
    project: ecomapp
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
