apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: ecom
data:
  MONGO: "true"
  MONGO_URL: mongodb://mongodb:27017/catalogue
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: catalogue
  namespace: ecom
  labels: 
    name: catalogue
    project: ecomApp
    tier: app
spec: 
  replicas: 1
  selector:
    matchLabels: 
      name: catalogue
      project: ecomapp
      tier: app
  template:
    metadata:
      labels:
        name: catalogue
        project: ecomapp
        tier: app
    spec: 
      containers: 
      - name: catalogue
        image: iamroyalreddy/ecom-catalogue:v2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1 
kind: Service
metadata:
  name: catalogue
  namespace: ecom
  labels:
    name: catalogue
    project: ecomapp
    tier: app
spec:
  selector:
    name: catalogue
    project: ecomapp
    tier: app
  ports:
  - port: 8080
    targetPort: 8080
