apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: ecom
data:
      CART_ENDPOINT: cart:8080
      DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: shipping
  namespace: ecom
  labels: 
    name: shipping
    project: ecomApp
    tier: app
spec: 
  replicas: 1
  selector:
    matchLabels: 
      name: shipping
      project: ecomapp
      tier: app
  template:
    metadata:
      labels:
        name: shipping
        project: ecomapp
        tier: app
    spec: 
      containers: 
      - name: shipping
        image: iamroyalreddy/ecom-shipping:v2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1 
kind: Service
metadata:
  name: shipping
  namespace: ecom
  labels:
    name: shipping
    project: ecomapp
    tier: app
spec:
  selector:
    name: shipping
    project: ecomapp
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
