apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: ecom
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/user"
  REDIS_URL: "redis://redis:6379"
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: user
  namespace: ecom
  labels: 
    name: user
    project: ecomapp
    tier: app
spec: 
  replicas: 1
  selector:
    matchLabels: 
      name: user
      project: ecomapp
      tier: app
  template:
    metadata:
      labels:
        name: user
        project: ecomapp
        tier: app
    spec: 
      containers: 
      - name: user
        image: iamroyalreddy/ecom-user:v2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: ecom
  labels:
    name: user
    project: ecomapp
    tier: app
spec:
  selector:
    name: user
    project: ecomapp
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
